### PR TITLE
fix: various fixes

### LINKED ISSUE #462: The alphabetical titles (C in this example) are not quite at the top of the page, so the contacts scroll under them
image

### LINKED ISSUE #464: Profile / Offline payments layout bug
image

### LINKED ISSUE #468: Send/Receive: Layout is wrong after adding tag (iOS)
`<BottomSheet keyboardBlurBehavior="restore" />` does not finish before navigating back.

https://user-images.githubusercontent.com/155891/194560487-e72259de-8de3-486b-8865-2671ff57e52e.MP4

### LINKED ISSUE #476: Send: Improve scrolling behavior in ContactList
**Describe the bug**
The ScrollView in ContactList behaves buggy when rendered inside BottomSheet.

**To Reproduce**
1. Add some contacts
2. Go to 'Send'
3. Click on 'Contacts icon'
4. Try to scroll down the list

**Expected behavior**
List should always scroll, maybe prevent BottomSheet "drag to close" functionality when there is a ScrollView.

**Screenshots**

https://user-images.githubusercontent.com/8538369/194703722-0d4e1ae8-508e-4505-a554-43bf0740c2e4.mp4

### PR DESCRIPTION
**Pull request by pwltr**
Closes #476 #462 #464

### Changes
- fix(lightning): NumberPad, copy, spacing
- fix(send): #468 quickfix for button
- fix(send): #476 ContactList scrolling
- fix(contacts): #462 ContactList sticky headers
- fix(profile): #464 remove divider
- fix(backup): bottomSheet size
- fix(onboarding): line up Welcome content with Slideshow on iOS
- fix(ui): glow preventing click

### Preview

https://user-images.githubusercontent.com/8538369/194710434-9a905bbc-7535-4118-8c38-5f6de527eea4.mp4

### CODE REVIEW

File: src/components/ContactsList.tsx [hunk 1]
```diff
@@ -115,30 +118,36 @@ const ContactsList = ({
...
+			);
+		},
+		[sectionBackgroundColor, sectionedContacts],
+	);
+
+	const renderItem = useCallback(
+		({ item: contact }): ReactElement => (
+			<ContactItem contact={contact} onPress={onPress} />
+		),
+		[],
```
Comment (limpbrains) [inline src/components/ContactsList.tsx]: eslint warning

File: src/components/ContactsList.tsx [hunk 2]
```diff
@@ -115,30 +118,36 @@ const ContactsList = ({
...
 
+	const List = bottomSheet ? BottomSheetSectionList : SectionList;
+
+	const renderSectionHeader = useCallback(
+		({ section: { title } }): ReactElement => {
+			const isFirst = title === sectionedContacts[0].title;
+			return (
+				<ThemedView
+					color={sectionBackgroundColor}
+					style={[!isFirst && styles.sectionSpacing]}>
```
Comment (limpbrains) [inline src/components/ContactsList.tsx]: no need to use an array here

File: src/screens/Wallets/SendOnChainTransaction/SendNumberPad.tsx [hunk 3]
```diff
@@ -25,12 +25,14 @@ import {
...
 import { useBottomSheetBackPress } from '../../../hooks/bottomSheet';
+import { useSafeAreaInsets } from 'react-native-safe-area-context';
 
 /**
  * Handles the number pad logic (add/remove/clear) for on-chain transactions.
  */
 const SendNumberPad = (): ReactElement => {
-	const snapPoints = useMemo(() => [425], []);
+	const insets = useSafeAreaInsets();
+	const snapPoints = useMemo(() => [400 + insets.bottom], []);
```
Comment (limpbrains) [inline src/screens/Wallets/SendOnChainTransaction/SendNumberPad.tsx]: eslint warning

**Review by limpbrains — CHANGES_REQUESTED** [review]

**Review by limpbrains — APPROVED** [review]
