### PR TITLE
feat: Buy Bitcoin with bitfinex, Secure your wallet, fix ordering

### LINKED ISSUE #385: Suggestions: gap space after closing suggestions cards
**Describe the bug**
There is a gap space after closing suggestions cards

**To Reproduce**
1. close all the cards at the homepage.

**Screenshots**
image

### LINKED ISSUE #428: Wallet: Suggestion Cards Findings
### Tasks:
- [x] remove "Secure your wallet" card
- [x] add "Buy Bitcoin" card + view
- [x] fix the ordering (see prototype)
- [x] update visual appearance of "Lightning pending" card (after setting up a channel)
- [ ] restore all cards on "Reset Suggestions"

### PR DESCRIPTION
**Pull request by limpbrains**
- new Buy Bitcoin with bitfinex screen
- removed Secure your wallet card
- fixed card ordering
- fixed no items in Carousel bug

### CODE REVIEW

File: src/screens/BuyBitcoin.tsx [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+				/>
+				<View style={styles.imageContainer}>
+					<Image
+						style={styles.image2}
+						source={require('../assets/illustrations/b-emboss.png')}
+					/>
+				</View>
+				<View style={styles.textContent}>
+					<Display>
+						Bitcoin <Display color="orange">for Bitkit.</Display>
```
Comment (pwltr) [inline src/screens/BuyBitcoin.tsx]: add a line-break here

**Review by pwltr — CHANGES_REQUESTED** [review]

**Review by pwltr — APPROVED** [review]
