### PR TITLE
fix(settings): Fix Support Link

### LINKED ISSUE #1095: [Bug]: Support button not working
### Describe the bug

Under settings->about one can find a support button. 

Unfortunately it’s not doing anything :) 

### Reproduce

1. Go to 'settings' (right top corner)
2. Click on 'About BitKit'
3. Click on ‘Support’
4. Nothing happens 

### Screenshots / Recording

_No response_

### Operating system

iOS 16.4.1

### Bitkit version

1.0 (64)

### Log output

_No response_

### PR DESCRIPTION
**Pull request by coreyphillips**
### Description
- Adds fallback url to the support link.
- Adds `encodeURIComponent` to subject and body in `createSupportLink` method.

### Linked Issues/Tasks
- This fixes #1095

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### Tests
- [x] No test

### QA Notes
- Navigate to Settings->About Bitkit and tap Support on a live iOS/Android device.
    - Expected: Bitkit should either open the device's default mail client, open a drawer to select and open a mail client or fallback to use the synonym.to support page in the event a default mail client is not available on the device.

### CODE REVIEW

**Review by bonomat — APPROVED** [review]
Thank you for the fast fix.

**Review by pwltr — APPROVED** [review]

File: src/screens/Settings/About/index.tsx [hunk 1]
```diff
@@ -106,7 +106,11 @@ const About = ({
 						type: EItemType.button,
 						onPress: async (): Promise<void> => {
 							const link = await createSupportLink();
-							await openURL(link);
+							const openUrlSuccess = await openURL(link);
+							if (!openUrlSuccess) {
+								//If unable to open mail app for any reason, open contact page in browser.
+								await openURL('https://synonym.to/contact');
+							}
```
Comment (pwltr) [inline src/screens/Settings/About/index.tsx:113]: I think there are some other occurrences where this should be added

Comment (coreyphillips) [reply src/screens/Settings/About/index.tsx:113]: Agreed. We can open those as separate PR's.
