### PR TITLE
fix: improve ln setup logic

### LINKED ISSUE #1253: Fee for Opening a LN channel does not update properly
### Describe the bug

when we try and create a LN channel, I navigate to custom setup > Enter Custom Amount > Continue > When selecting different sizes of channel ($250 / $500 or $990) the Receiving Capacity Fee does not update for ANY of the amounts. If a user clicks continue then they will be presented with a different fee (depending on the size of channel they chose) which will lead to confusion. 

### Reproduce

1. Go to 'Open LN Channel'
2. Click on 'Custom Setup > Enter Amount (make note of the fee displayed) > Click continue (see new fee)

### Screenshots / Recording

_No response_

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v65 

### Log output

_No response_

### PR DESCRIPTION
**Pull request by limpbrains**
### Description

- move ln quick and transder setup to reselect, add tests
- custom setup ln screen, fetch fees everytime something changes

### Linked Issues/Tasks

closes #1253

### Type of change

Bug fix

### Tests

Unit test

### CODE REVIEW

File: src/screens/Lightning/CustomSetup.tsx [hunk 1]
```diff
@@ -110,7 +110,7 @@ const CustomSetup = ({
 	const blocktankInfo = useSelector(blocktankInfoSelector);
 
 	const [textFieldValue, setTextFieldValue] = useState('');
-	const [channelOpenFee, setChannelOpenFee] = useState('');
+	const [channelOpenFee, setChannelOpenFee] = useState<{}>({});
```
Comment (pwltr) [inline src/screens/Lightning/CustomSetup.tsx]: Should avoid using `{}` type

```suggestion
	const [channelOpenFee, setChannelOpenFee] = useState<{
		[key: string]: string;
	}>({});
```

File: src/utils/wallet/constants.ts [hunk 2]
```diff
@@ -14,6 +14,10 @@ export const CHUNK_LIMIT = 15;
 //How much of the users funds we allow to be used for Lightning.
 export const SPENDING_LIMIT_RATIO = 0.8;
 
+export const DIFF = 0.01;
```
Comment (pwltr) [inline src/utils/wallet/constants.ts]: Since we're export this variable now can we it a better name or add a comment so it's clear what it is for?

File: src/store/reducers/blocktank.ts [hunk 3]
```diff
@@ -9,6 +9,7 @@ const blocktank = (
 ): IBlocktank => {
 	switch (action.type) {
 		case actions.UPDATE_BLOCKTANK_INFO:
+			action.payload.options.max0ConfClientBalanceSat = 0;
```
Comment (pwltr) [inline src/store/reducers/blocktank.ts]: Why is this needed? The value from BT info is wrong?

**Review by pwltr — CHANGES_REQUESTED** [review]

**Comment by pwltr** [comment]
Not sure if it's a regression but when I try to select the largest card I can't continue with the order:

https://github.com/synonymdev/bitkit/assets/8538369/578b661f-7ec0-4d47-958e-dcc11fa4ae70

File: src/utils/wallet/constants.ts (hunk 2 above)
Comment (limpbrains) [reply src/utils/wallet/constants.ts]: LIGHTNIG_DIFF, lol, I can't think of anything better

File: src/store/reducers/blocktank.ts (hunk 3 above)
Comment (limpbrains) [reply src/store/reducers/blocktank.ts]: oops, that was debug code

**Comment by limpbrains** [comment]
> Not sure if it's a regression but when I try to select the largest card I can't continue with the order:

It is not, I believe bug existing for quite a while

File: src/utils/wallet/constants.ts (hunk 2 above)
Comment (pwltr) [reply src/utils/wallet/constants.ts]: better :)

**Review by pwltr — APPROVED** [review]
