### PR TITLE
fix: add switch unit logic to CJIT screen

### LINKED ISSUE #1790: [Bug]: Tapping on value at Receive Bitcoin screen for spending doesn't toggle currency
### Describe the bug

On the 'Receive Bitcoin' screen, that's shown when requesting spending balance, tapping on the bitcoin/fiat value does not toggle between the two (need to use the dedicated button). On other screens such as the main wallet view, 'Transfer Funds' and  'Edit Invoice' for onchain, tapping the value does toggle.

### Reproduce

1. Go to input an amount to receive for spending balance
2. Tap on the value
3. Value does not toggle between bitcoin and fiat

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/74595920/9c8c7a77-6aef-4a45-bbc8-4e6a04c7ec3e

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

2c5b07726fd35cb796a9566c47d0f6c36fda4ef4

### Log output

_No response_

### PR DESCRIPTION
**Pull request by limpbrains**
### Description

Add unit switching for CJIT screen

### Linked Issues/Tasks

closes #1790

### Type of change

Bug fix

### Tests

No test

### CODE REVIEW

File: src/screens/Wallets/Receive/ReceiveAmount.tsx [hunk 1]
```diff
@@ -76,12 +78,17 @@ const ReceiveAmount = ({
 	const onChangeUnit = (): void => {
 		const result = getNumberPadText(invoice.amount, denomination, nextUnit);
 		dispatch(updateInvoice({ numberPadText: result }));
+		switchUnit();
```
Comment (pwltr) [inline src/screens/Wallets/Receive/ReceiveAmount.tsx:81]: The unit button component already calls this function

**Review by pwltr — CHANGES_REQUESTED** [review]

File: src/screens/Wallets/Receive/ReceiveAmount.tsx (hunk 1 above)
Comment (limpbrains) [reply src/screens/Wallets/Receive/ReceiveAmount.tsx:81]: I see this problem in other places, like QuickSetup, ReceiveDetails
Maybe we should address it later ?

Comment (pwltr) [reply src/screens/Wallets/Receive/ReceiveAmount.tsx:81]: true let's do that

**Review by pwltr — APPROVED** [review]
