### PR TITLE
fix(backup): add boosts & transfers to backup

### LINKED ISSUE #1844: [Bug]: Restored wallet splits Boosted CPFP transactions into separate activities
### Describe the bug

When boosting a transaction, the existing activity is updated to reflect the change and combines the subtracted amounts. If the wallet is restored the transactions are displayed as separate activities. We should aim to keep the activity list constant after wallet restore.

### Reproduce

1. Send onchain funds using a fee rate that needs a boost
2. Boost the transaction
3. Observe the two transactions are combined in one activity
4. Restore the wallet
5. Observe the two transactions each now have their own activity

### Screenshots / Recording

In the following example, the final transaction in the CPFP chain is [d69eeb99e9a562e7b9a6a34abce3c77808e4e0f8a077058ee1558881ae209a2b](https://mempool.space/tx/d69eeb99e9a562e7b9a6a34abce3c77808e4e0f8a077058ee1558881ae209a2b)

Before restore, two activities are shown for a chain of three transactions. The top one had a boost and so combines two CPFP transactions and the bottom is a single transaction:

Screenshot 2024-05-17 at 15 59 17

-----

After restore there are three activities, one for each transaction in the CPFP chain:

Screenshot 2024-05-17 at 15 59 17

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

4980b42f4382c93137996ed30d7b68658a000786

### Log output

_No response_

### PR DESCRIPTION
**Pull request by pwltr**
### Description

Adds `boostedTransactions` and `transfers` from wallet state to backup & restore.

### Linked Issues/Tasks

Closes https://github.com/synonymdev/bitkit/issues/1844 https://github.com/synonymdev/bitkit/issues/1868

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [x] Detox test
- [x] Unit test
- [ ] No test

### Screenshots

Simulator Screenshot - iPhone 16 - 2024-11-26 at 17 10 08

Screenshot shows activity after restore:
- 1 received tx
- 1 sent tx not boosted (1000 sats)
- 1 sent tx boosted (1000 sats)
- 2 transfers to spending

### CODE REVIEW

File: src/utils/helpers.ts [hunk 1]
```diff
@@ -242,6 +242,66 @@ export const isObjPartialMatch = (
 	});
 };
 
+export const deepCompareStructure = (
```
Comment (limpbrains) [inline src/utils/helpers.ts:248]: we have lodash, maybe just use it?

**Comment by limpbrains** [comment]
I think we should merge this

File: src/utils/helpers.ts (hunk 1 above)
Comment (pwltr) [reply src/utils/helpers.ts:248]: There is no lodash util that covers all of this, but I refactored it to use lodash where possible.

File: e2e/boost.e2e.js [hunk 2]
```diff
@@ -267,10 +269,23 @@ d('Boost', () => {
 		assert(Number(oldFee.replace(' ', '')) < Number(newFee.replace(' ', '')));
 		assert(oldTxid !== newTxid);
 		await expect(element(by.id('RBFBoosted'))).toBeVisible();
+		await element(by.id('NavigationClose')).atIndex(0).tap();
+
+		// wipe & restore
+		const seed = await getSeed();
+		await restoreWallet(seed);
```
Comment (limpbrains) [inline e2e/boost.e2e.js:276]: Nice

**Review by limpbrains — APPROVED** [review]

**Comment by catch-21** [comment]
Tested on https://github.com/synonymdev/bitkit/tree/release-v1.0.7

- [x] Normal send boosted (RBF)

The following checks are for successful back up and restore:
- [ ] Ongoing Transfer from Savings
- [ ] Confirmed Transfer from Savings
- [ ] Boosted ongoing Transfer from Savings
- [ ] Boosted confirmed Transfer from Savings
- [x] Ongoing Transfer from Spending
- [ ] Confirmed Transfer from Spending
- [x] Boosted ongoing Transfer from Spending
  - Works but still shows the separate 'Sent' activity for the CPFP tx, which is redundant given the 'Boosting' transfer activity, see screenshot and video below



https://github.com/user-attachments/assets/62f62c3b-649c-42ba-b8e2-d0f420190343

- [ ] Boosted confirmed Transfer from Spending
  - This restored as separate Received and Sent activities (first is the transfer and second is the cpfp boost), see screenshots below.

**Comment by pwltr** [comment]
> Tested on https://github.com/synonymdev/bitkit/tree/release-v1.0.7
> 
> The following checks are for successful back up and restore:
> 
> * [ ]  Ongoing Transfer from Savings
> * [ ]  Confirmed Transfer from Savings
> * [ ]  Boosted ongoing Transfer from Savings
> * [ ]  Boosted confirmed Transfer from Savings
> * [x]  Ongoing Transfer from Spending
> * [ ]  Confirmed Transfer from Spending
> * [ ]  Boosted ongoing Transfer from Spending
> * [ ]  Boosted confirmed Transfer from Spending

Thanks for this list, I only tested transfer to spending and boosting basic send. Will revisit this again.
