### PR TITLE
Slashtags UI Profile/Contacts various fixes

### LINKED ISSUE #345: Profile: change create profile screen layout
**Describe the bug**
- [x] Use dark keyboard
- [x] Change button label to ‘‘Add Link’
- [x] Check/fix button padding (left/right)

**Screenshots**
image

### LINKED ISSUE #346: Profile: change Payment Setup screen
**Describe the bug**
- [x] Use different graphic
- [x] Copy heading: ‘Pay your Contacts’
- [x] Copy paragraph: “You and your contacts can use Bitkit to send payments directly, without banks, anytime, anywhere.’
- [x] Change title to ‘Pay Contacts’
- [x] Change all ‘Continue’ to ‘Next’ on buttons
- [x] Check layout, location of elements etc

**Screenshots**
image

### LINKED ISSUE #347: Contacts: review contact intro screen
**Describe the bug**
- [x] Please check layout details like location of button, other UI elements. Orange appears to be a different color value but could be because of screenshot (should be #ff6600)
- [x] Copy: ‘Use Bitkit to get automatic updates from your contacts, pay them, and follow their public profiles.’

**Screenshots**
image

### LINKED ISSUE #348: Contacts: review add new contact screen
**Describe the bug**

- [x] Please note the spacing between the actions scan/paste
- [x] Copy: ‘Add a new contact by scanning a QR or by pasting their key below.’
- [x] Copy field label: ‘Add contact’
- [x] Copy input field: ‘Paste a key’

**Screenshots**
image

### LINKED ISSUE #350: Contacts: review contact list
**Describe the bug**
- [ ] Bug: contact keys without contact info
- [ ] Bug: ‘undefined’‘ 
- [x] Check size of [+] button (should be same height as search bar)

**Screenshots**
image

### PR DESCRIPTION
**Pull request by limpbrains**
closes #350 #345 #348 #346 #347

### CODE REVIEW

File: src/screens/Contacts/Contacts.tsx [hunk 1]
```diff
@@ -164,15 +163,14 @@ const ContactsScreen = ({ navigation }): JSX.Element => {
 				<View style={styles.modalContainer}>
 					<Subtitle style={styles.modalTitle}>Add a contact</Subtitle>
```
Comment (pwltr) [inline src/screens/Contacts/Contacts.tsx]: Should be "Add Contact"

On Android the placeholder for the TextField is missing:
Screenshot_1662719326

**Review by pwltr — CHANGES_REQUESTED** [review]

File: src/screens/Contacts/Contacts.tsx (hunk 1 above)
Comment (limpbrains) [reply src/screens/Contacts/Contacts.tsx]: fixed

**Review by pwltr — APPROVED** [review]
