### PR TITLE
fix: various fixes

### LINKED ISSUE #495: Send/Receive: Confetti not animated on some phones
Some users are not seeing the confetti animated when sending (Result screen) or receiving (Payment Received modal) a payment.

### PR DESCRIPTION
**Pull request by pwltr**
Closes #495 

Mostly fixes from Bitkit build v21 findings Google Doc

### Changes
- fix(settings): auth protected routes
- fix(ui): #495 force lottie autoplay
- fix(settings): update RadioButtonGroup
- fix(assets): small fixes for BitcoinBreakdown
- fix(settings): update LightningNodeInfo
- fix lint some warnings

### CODE REVIEW

File: src/components/ProfileLinks.tsx [hunk 1]
```diff
@@ -28,7 +28,8 @@ const ProfileLinks = ({
 			) : (
 				links.map((link): JSX.Element => {
 					const trimmedUrl = link.url
-						.replace('https://www.', '')
+						.replace('https://', '')
+						.replace('www.', '')
```
Comment (limpbrains) [inline src/components/ProfileLinks.tsx:32]: technically www.domain.com and domain.com may act very different. 
I wouldn't decide for the user

**Review by limpbrains — APPROVED** [review]

File: src/components/ProfileLinks.tsx (hunk 1 above)
Comment (pwltr) [reply src/components/ProfileLinks.tsx:32]: This is just the display text to make it a bit shorter, the link itself is not changed. Or do you think we should not shorten the text?

Comment (limpbrains) [reply src/components/ProfileLinks.tsx:32]: No, I don't think so.
This is fine then
