### PR TITLE
fix: #466 slashtags Auth screen

### LINKED ISSUE #466: Slashtags layout bug
image

### PR DESCRIPTION
**Pull request by limpbrains**
closes #466

### CODE REVIEW

**Review by Nuhvi — APPROVED** [review]

File: src/screens/Widgets/SlashAuthModal.tsx [hunk 1]
```diff
@@ -175,7 +178,7 @@ const _SlashAuthModal = (): ReactElement => {
 };
 
 export const SlashAuthModal = (): ReactElement => {
-	const snapPoints = useMemo(() => [650], []);
+	const snapPoints = useMemo(() => [700], []);
```
Comment (pwltr) [inline src/screens/Widgets/SlashAuthModal.tsx]: Please `useSnapPoints('large')` to keep consistent BottomSheet sizing

**Review by pwltr — CHANGES_REQUESTED** [review]

**Review by pwltr — APPROVED** [review]
