### PR TITLE
fix(receive): CJIT activity not added when app in background

### LINKED ISSUE #1780: [Bug]: No confetti or transaction activity on requesting spending balance via CJIT
### Describe the bug

Although the channel setup completed (see Created cjitEntry ef5d90a2-7d12-417b-8163-30db71dc814e) I did not see any confetti or transaction activity. After manually refreshing the wallet the balance updated to reflect my new spending balance. After a short wait and restarting the app I still do not see the transaction activity. Other new wallet have not seen this issue. This is occurring on a wallet that recently had a force closure (could be relevant).

It is possible to produce a CJIT invoice, but if Bitkit isn't in the foreground when the invoice is paid then it is possible for it to not detect the 'Received' event. This leads to correct spending balance but no activity to assure the user the payment was received.

### Reproduce

1. Start with a Bitkit wallet with no LN channels
2. Tap Receive and produce CJIT invoice
3. Screenshot the invoice
4. Minimise Bitkit
5. Scan to pay the invoice from a different wallet. The LN payment will succeed provided Bitkit is still running in the background. If Bitkit has been killed then LN payment fails and the invoice goes from Pending to Holding to Cancelled state.
6. Now you can kill Bitkit (or leave it for the OS to dispose of after some time)
7. Start Bitkit again
8. Observe new spending balance, but no confetti and no 'Received' activity item. Also observe open Lightning connection in Advanced settings.

### Screenshots / Recording

This shows my correct balance and LN channel is open but no transaction activity

https://github.com/synonymdev/bitkit/assets/74595920/34274d3d-c245-40ab-965b-608d607527ba

### Operating system

Android/iOS

### Bitkit version

1.0.4 (135)

### Log output

[bitkit_ldk_logs_1714731123960.zip](https://github.com/synonymdev/bitkit/files/15198712/bitkit_ldk_logs_1714731123960.zip)

### PR DESCRIPTION
**Pull request by pwltr**
### Description

In the common scenario where a user created a CJIT invoice and then paid from another LN wallet on the same phone (putting Bitkit in the background) a couple of issues arise.

- `refreshLdk()` is calling `lm.syncLdk()` which hangs when the app is in the background blocking further execution
- `addCJitActivityItem` only checked for open channels, it should also consider pending channels (currently opening)
- `redux-persist` doesn't flush the state to the database when the app is in the background because it uses `setInterval()`, quickfix by manually calling `flush()` for now

### Note

I wasn't able to reproduce this issue on iOS since network connection was always cut immediately for me when putting the app to the background causing the hold invoice to never resolve. Hopefully these fixes work on iOS as well.

### Linked Issues/Tasks

Closes https://github.com/synonymdev/bitkit/issues/1780

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### Screenshot / Video

https://github.com/user-attachments/assets/34f3e203-577c-44c7-8a38-9dc0810221e0

### QA Notes

Use reproduction steps from https://github.com/synonymdev/bitkit/issues/1780

### CODE REVIEW

File: src/store/utils/activity.ts [hunk 1]
```diff
@@ -33,31 +34,15 @@ export const addCJitActivityItem = async (channelId: string): Promise<void> => {
...
-	let cJitEntry: ICJitEntry | undefined;
-	let i = 0;
-	while (!cJitEntry && i < 5) {
-		await sleep(1000); // wait until Blocktank has updated its database.
-		await updatePendingCJitEntries();
-		cJitEntry = cJitEntries.find((entry) => {
-			return entry.channel?.fundingTx.id === channel.funding_txid;
-		});
-		i++;
-	}
```
Comment (pwltr) [inline src/store/utils/activity.ts:48]: I'm removing this code block since this check never succeeds, probably because Blocktank takes too long to update.

**Review by coreyphillips — APPROVED** [review]
