### PR TITLE
fix(transfer): show transfer UI for force-closes

### LINKED ISSUE #1779: [Bug]: Show pending balance for force closes
### Describe the bug

Bitkit needs to show pending transfer UI when a channel is force closed. 

pending balance, card, activity item

https://app.asana.com/0/1189635884316057/1205269092901302/f
https://app.asana.com/0/0/1204208728352470/1206703239419962/f

### Reproduce

1. Open a channel
2. Either force close from client or LSP
3. Should see pending transfer UI

### Screenshots / Recording

_No response_

### Operating system

Android, iOS

### Bitkit version

116

### Log output

_No response_

### LINKED ISSUE #1818: [Bug]: Activity for transferring from spending to saving always assumed 60m to confirm
### Describe the bug

When closing a LN channel to move funds from spending to saving, the transaction activity displayed in Bitkit always starts by showing +60m to confirm, even if it will make it into the next block or if it has already confirmed. It should behave like a normal transaction activity and show a realistic confirmation estimation

### Reproduce

1. With some funds in spending balance
2. Close the LN channel from settings page
3. View the estimated time for new activity and compare with actual in the mempool/onchain

### Screenshots / Recording

Screenshot 2024-05-10 at 15 24 32

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

v117 ae82edd7a3ab8ff771cbf945729e41c43c5ed1f2

### Log output

_No response_

### PR DESCRIPTION
**Pull request by pwltr**
### Description

- Adds transfer UI for force-closed channels. Removes it for mutual closes.
- Removes `claimableBalances` from `lighting.store` and moves it to the respective channel together with a `closureReason`
- Adds "force close channels" developer action

**Known Issues:**
- transfer duration sometimes not updating (bug w/ claimable balance from LDK)
- activity item only shows up after transfer completed
- force close pending balance doesn't account for sweep tx fee
- balances wrong for a second when sweep from force close comes in

### Linked Issues/Tasks

Closes https://github.com/synonymdev/bitkit/issues/1779 https://github.com/synonymdev/bitkit/issues/1818

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (improving code without creating new functionality)

### Tests

- [ ] Detox test
- [ ] Unit test
- [x] No test

### Screenshot / Video

https://github.com/synonymdev/bitkit/assets/8538369/9750f521-194f-438e-a2ec-9574b4295f46

### QA Notes

Open and (force) closing channels should show the expected UI.

### CODE REVIEW

File: src/components/Suggestions.tsx [hunk 1]
```diff
@@ -117,8 +118,12 @@ const Suggestions = (): ReactElement => {
...
 		({ item }: { item: ITodo }): ReactElement => {
 			const title = t(`${item.id}.title`);
-			const duration = item.duration;
-			let description = t(`${item.id}.description`, { duration });
+			let description = t(`${item.id}.description`);
+
+			if (item.confirmsIn) {
+				const duration = getDurationForBlocks(item.confirmsIn);
+				description = t(`${item.id}.description`, { duration });
+			}
```
Comment (limpbrains) [inline src/components/Suggestions.tsx:126]: we need to improve getDurationForBlocks internationalization in future

**Review by limpbrains — APPROVED** [review]

File: src/components/Suggestions.tsx (hunk 1 above)
Comment (pwltr) [reply src/components/Suggestions.tsx:126]: Yeah I need to do some copy changes in another PR. Will include a change for this.

**Comment by catch-21** [comment]
Tested on https://github.com/synonymdev/bitkit/commit/658b9f2bd22d2ca63893a89dc56f47a054546d79
See https://github.com/synonymdev/bitkit/issues/1779#issuecomment-2123304618
