### PR TITLE
fix: show channel if inbound_scid_alias is not set

### LINKED ISSUE #1490: [Bug]: LNURL-Channel doesn't work properly
### Describe the bug

After scanning lnurl-channel it usually needs a few app restarts to finally open a channel

Also on channel details this new channel has no name before it is opened 

### Reproduce

1. Scan LNURL-channel
3. Watch the app

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/155891/1473abdf-e83b-4bad-a01f-bc9bc2e24cc6

### Operating system

iOS

### Bitkit version

v94

### Log output
[bitkit_ldk_logs_1705059027826.zip](https://github.com/synonymdev/bitkit/files/13918516/bitkit_ldk_logs_1705059027826.zip)

### PR DESCRIPTION
**Pull request by limpbrains**
### Description

When I'm opening a channel using LNURL-channel from Blocktank I see no channel id on channels list screen.
This is because `inbound_scid_alias` is set to empty string.

For example:
```
{ user_channel_id: 'a9a7f5d70c3f0cae011c66adceda72d4',
  outbound_capacity_sat: 46053,
  inbound_capacity_sat: 45407,
  unspendable_punishment_reserve: 354,
  confirmations: 0,
  channel_id: '080ab26d5d95f343ae632418fc674b13d7c75003df1b2318bb6ce539d5f1e823',
  counterparty_node_id: '03b9a456fb45d5ac98c02040d39aec77fa3eeb41fd22cf40b862b393bcfc43473a',
  inbound_payment_scid: null,
  config_forwarding_fee_proportional_millionths: 0,
  is_channel_ready: false,
  balance_sat: 46407,
  is_public: false,
  funding_txid: '23e8f1d539e56cbb18231bdf0350c7d7134b67fc182463ae43f3955d6db20a08',
  confirmations_required: 1,
  is_outbound: false,
  config_forwarding_fee_base_msat: 1000,
  channel_type: '401000',
  force_close_spend_delay: 144,
  short_channel_id: '',
  channel_value_satoshis: 92814,
  is_usable: false,
  inbound_scid_alias: '' }
  ```

Also I've fixed LN connection card now shows during second LN channel opening

### Linked Issues/Tasks

closes #1490

### Type of change

Bug fix

### Tests

No test

### Screenshot / Video

Simulator Screenshot - iPhone 15 Pro - 2024-01-16 at 12 21 29

### CODE REVIEW

File: src/store/reselect/todos.ts [hunk 1]
```diff
@@ -127,6 +127,8 @@ export const todosFullSelector = createSelector(
 				res.push(transferToSpendingTodo);
 			} else if (balanceInTransfer?.amount_satoshis) {
 				res.push(transferToSavingsTodo); // TODO: find a way to distinguish between transfer to and from spendings
+			} else if (pendingChannels.length > 0) {
+				res.push(lightningConnectingTodo);
```
Comment (pwltr) [inline src/store/reselect/todos.ts:131]: I think for transfers to spending this will show both the 'setting up' card as well as the 'transfer' card?

**Review by pwltr — APPROVED** [review]
