### PR TITLE
fix: during slashtags migration do not save image

### LINKED ISSUE #1325: Unable To Save Contact
I haven't created a profile and I don't have any contacts. Yet, I'm randomly getting this error toast message on build 79.

image

### PR DESCRIPTION
**Pull request by limpbrains**
### Description

During slashtags migration do not save image because it can be too big.

### Linked Issues/Tasks

closes #1325

### Type of change

Bug fix

### Tests

No test

### CODE REVIEW

**Review by coreyphillips — APPROVED** [review]

File: src/hooks/slashtags2.ts [hunk 1]
```diff
@@ -176,6 +176,13 @@ export const useMigrateSlashtags2 = (): void => {
...
 
-		saveProfile2(url, oldProfile, slashtagsProfile);
+		// save everything, except image becase it can be too big
+		const p = {
+			bio: oldProfile.bio,
+			name: oldProfile.name,
+			links: oldProfile.links,
+		};
+
+		saveProfile2(url, p, slashtagsProfile);
```
Comment (MiguelMedeiros) [inline src/hooks/slashtags2.ts:186]: Just a suggestion to make the code a bit cleaner and concise using destructuring. It's not a mandatory fix, just a tip! 😊

```suggestion
		// save everything, except image because it can be too big
		const { bio, name, links } = oldProfile;
		saveProfile2(url, { bio, name, links }, slashtagsProfile);
```
