### PR TITLE
fix: lnurl-channel and lnurl tests

### LINKED ISSUE #569: add to Bitkit LNURL Open channel

### PR DESCRIPTION
**Pull request by limpbrains**
### Description

- change lnurl-channel flow to have confurmation/success screens
- rename DEBUG env variable to DEV in e2e tests. This allows to debug other libs, like lnurl or express
`DEBUG="lnurl* lnurl server" DEBUG_ENABLED=true npx detox test --configuration ios.debug e2e/lnurl.e2e.js`
- new e2e lnurl test that covers lnurl-withdraw/pay/channel/auth. 

### Linked Issues/Tasks

closes #569
https://app.asana.com/0/home/1201997517558994/1205221705710380

### Type of change

Bug fix

### Tests

Detox test

### Screenshot / Video

https://github.com/synonymdev/bitkit/assets/155891/70a0eb7c-5505-46c3-87c3-367caa00fa82

### CODE REVIEW

File: src/utils/lnurl.ts [hunk 1]
```diff
@@ -312,14 +322,16 @@ export const handleLnurlWithdraw = async ({
 		return err(callbackRes.error.message);
 	}
 
-	const channelStatusRes = await fetch(callbackRes.value);
-	if (channelStatusRes.status !== 200) {
+	let channelStatusRes: any;
```
Comment (pwltr) [inline src/utils/lnurl.ts]: To avoid `let channelStatusRes: any;`

```suggestion
try {
		const channelStatusRes = await fetch(callbackRes.value);
		const jsonRes = await channelStatusRes.json();

		if (jsonRes.status === 'ERROR') {
			showToast({
				type: 'error',
				title: i18n.t('other:lnurl_withdr_error'),
				description: jsonRes.reason,
			});
			return err(jsonRes.reason);
		}

		showToast({
			type: 'success',
			title: i18n.t('other:lnurl_withdr_success_title'),
			description: i18n.t('other:lnurl_withdr_success_msg'),
		});

		return ok({ type: EQRDataType.lnurlWithdraw });
	} catch (e) {
		showToast({
			type: 'error',
			title: i18n.t('other:lnurl_withdr_error'),
			description: e.message,
		});
		return err(e.message);
	}
```

File: src/utils/lnurl.ts [hunk 2]
```diff
@@ -68,11 +68,21 @@ export const handleLnurlPay = async ({
 
 	const milliSats = Math.floor(amountSats * 1000);
 
-	const callbackRes = await lnurlPay({
-		params,
-		milliSats,
-		comment: 'Bitkit LNURL-Pay',
-	});
+	let callbackRes: any;
```
Comment (pwltr) [inline src/utils/lnurl.ts]: To avoid `let channelStatusRes: any;`

```suggestion
try {
		const callbackRes = await lnurlPay({
			params,
			milliSats,
			comment: 'Bitkit LNURL-Pay',
		});

		if (callbackRes.isErr()) {
			showToast({
				type: 'error',
				title: i18n.t('other:lnurl_pay_error'),
				description: callbackRes.error.message,
			});
			return err(callbackRes.error.message);
		}

		return ok(callbackRes.value.pr);
	} catch (e) {
		showToast({
			type: 'error',
			title: i18n.t('other:lnurl_pay_error'),
			description: e.message,
		});
		return err(e.message);
	}
```

File: package.json [hunk 3]
```diff
@@ -178,13 +180,14 @@
     "bitcoin-json-rpc": "^1.2.7",
     "browserify-zlib": "^0.2.0",
     "dns.js": "^1.0.1",
-    "electrum-client": "github:BlueWallet/rn-electrum-client#76c0ea35e1a50c47f3a7f818d529ebd100161496",
+    "electrum-client": "github:BlueWallet/rn-electrum-client#47acb51149e97fab249c3f8a314f708dbee4fb6e",
```
Comment (pwltr) [inline package.json:183]: Maybe add to `yarn.lock` as well if important

**Review by pwltr — CHANGES_REQUESTED** [review]

File: package.json
Comment (pwltr) [inline package.json:1]: have to rename `DEBUG=true` to `DEV=true` to avoid breaking tests in development

**Review by pwltr — CHANGES_REQUESTED** [review]

**Review by pwltr — APPROVED** [review]
